config/routes.rb
Hrita::Application.routes.draw do
  devise_for :users

  root :to => 'employees#index'
  resources :employees
  

end

app/models/department.rb
class Department < ActiveRecord::Base
  has_many :divisions
end

app/models/division.rb
class Division < ActiveRecord::Base
  belongs_to :department 
  has_many :employees
end

app/models/employee.rb
require "#{Rails.root.to_s}/lib/paperclip_processors/cropper.rb"
include Paperclip

class Employee < ActiveRecord::Base
  
  
  
  CATEGORIES = {
    1 => ["Crew Operator", ],
    2 => ["Foreman", "Staff", "Kepala Regu", "Administrasi"],
    3 => ["Supervisor"],
    4 => ["Superintendent"],
    5 => ["Deputy GM", "Manager"],
    6 => ["GM"]
  }
  
  DEPARTMENTS = {
    1 => "Explorasi",
    2 => "Finance",
    3 => "General Affair",
    4 => "HRD",
    5 => "Survey Tambang",
    6 => "Produksi",
    7 => "Comdev",
    8 => "Preparasi",
    9 => "Quality Control",
    10 => "Shipping",
    11 => "HSE",
    12 => "Logistik", 
    13 => "Maintenance",
    14 => "Konstruksi",
    15 => "Grade Control",
    16 => "Purchasing", 
    17 => "Elektrik",
    18 => "Security" 
  }
  
  
  
  
  # belongs_to :department
  
    # the greater sign (>) instructs the scaling to preserve width:length ratio 
    # so that there will be no distortion
  has_attached_file :photo, 
    :styles => { :small => "100x100>", :profile => "200x200>" , :large => "300x300>" },
    :processors => [:cropper]  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h  
  after_update :reprocess_photo, :if => :cropping? 
  
  
  
  # validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  
  # model relation
  belongs_to :division
  belongs_to :position
  def cropping?  
    puts "We are in the cropping?\n"*5
    iscrop = !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?  
    puts "The value of cropping? is #{iscrop}"
    iscrop
  end  

  def photo_geometry(style = :original)  
    @geometry ||= {}  
    @geometry[style] ||= Paperclip::Geometry.from_file(photo.path(style))  
  end

  # def category_selections
  #     category_selections_result = {}
  #     
  #     CATEGORIES.each do | key , values | 
  #       for value in values 
  #         category_selections_result[value] = key
  #       end
  #     end
  #     
  #     category_selections_result
  #   end
  

  def self.position_selections
    position_selections_result = {}
    
    Position.all.each do | position | 
        position_selections_result[position.title] = position.id
    end
    
    position_selections_result
  end
  
  def self.grouped_selection_for_divisions
    grouped_selections = {}
    
    Department.all.each do | department |
      division_selections = []
      department.divisions.each do | division |
        division_selections << [ division.name, division.id ]
      end
      grouped_selections[department.name] = division_selections
    end
    
    grouped_selections 
  end

  private  
  def reprocess_photo
    puts "We are gonna reprocess the photo\n"*10
    photo.reprocess!  
  end
  
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :employees
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  def index 
    @employees = Employee.all 
    @new_employee = Employee.new
  end
  
  def new
    @employee = Employee.new 
  end
  
  
  def show
    @employee = Employee.find_by_id( params[:id]  ) 
  end

  # def create  
  #   @employee = Employee.new(params[:employee])  
  #   
  #   if @employee.save  
  #     puts "Yeah saved!"
  #     flash[:notice] = "Successfully created user."  
  #     if params[:employee][:photo].blank?  
  #       redirect_to @employee  
  #     else  
  #       render :action => 'crop'  
  #     end  
  #   else  
  #     puts "Save is failing"
  #     render :action => 'new'  
  #   end  
  # end
  
  def create  
    @employee = Employee.new(params[:employee])  
    
    if @employee.save  
      puts "Yeah saved!"
      flash[:notice] = "Successfully created user."  
      # if params[:employee][:photo].blank?  
      #   redirect_to @employee  
      # else  
      #   render :action => 'crop'  
      # end  
      redirect_to @employee  
    else  
      puts "Save is failing"
      render :action => 'new'  
    end  
  end
  
  
  def update  
    @employee = Employee.find(params[:id])  
    if @employee.update_attributes(params[:employee])  
      flash[:notice] = "Successfully updated user."  
      if params[:employee][:photo].blank?  
        puts "BOOM BOOM employee photo is blank"
        redirect_to @employee  
      else  
        puts "Gonna render crop"
        render :action => 'crop'  
      end  
    else  
      puts "gonna play with edit"
      render :action => 'edit'  
    end  
  end

  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/employees/_brief_profile.erb
<div class="profile-content clearfix">
	<div class="photo-column">
		<%= image_tag employee.photo.url(:profile) , :class => "profile-pic"%>
	</div>
	
	<div class="personal-info-column">
		<h2><%= employee.name %></h2>
		<table>
			<tr>
				<td class="label">
					NIK
				</td>
				<td class="value">
					<%= employee.nik %>
				</td>
			</tr>
			<tr>
				<td class="label">
					Department
				</td>
				<td class="value">
					<%= employee.division.department.name %>
				</td>
			</tr>
			
			<tr>
				<td class="label">
					Division
				</td>
				<td class="value">
					<%= employee.division.name %>
				</td>
			</tr>
			
			<tr>
				<td class="label">
					Jabatan
				</td>
				<td class="value">
					<%= employee.position.title %>
				</td>
			</tr>
			
			<tr>
				<td class="label">
					Start Date
				</td>
				<td class="value">
					<%= employee.starting_date %>
				</td>
			</tr>
	
		</table>
	</div>
</div>

app/views/employees/_employee_details.html.erb
<!-- For Education and Training -->

<div class="item-container"> <!-- each section is enclosed within the item-container -->
	<div class="item-detail">
		<ol start="1">
			<li>
				<div class="wrapper">
					<div class="headline">Education and Training</div>
					<div class="summary-content">
						<div class="entry">
							<%= "January 2008 - September 2008, POP Training, Internal GPS "%>
						</div>
						
						<div class="entry">
							<%= "September 2008 - January 2009, Pelatihan Teknik Dasar Tambang, ITB "%>
						</div>
						
						<div class="entry">
							<%= "July 2009 - Desember 2010, KTT Training, Universitas Parahyangan "%>
						</div>
					</div>
				</div>
			</li>
		</ol>
	</div>
</div> <!-- item-container -->


<!-- For Education and Training -->

<div class="item-container"> <!-- each section is enclosed within the item-container -->
	<div class="item-detail">
		<ol start="1">
			<li>
				<div class="wrapper">
					<div class="headline">Reward</div>
					<div class="summary-content">
						<div class="entry">
							<%= "Desember 2010  - February 2011, Extra 1 bulan cuti roster "%>
						</div>
						
						<div class="entry">
							<%= "Maret 2009, Extra 3 bulan gaji untuk perawatan kendaraan operasional "%>
						</div>
						
					</div>
				</div>
			</li>
		</ol>
	</div>
</div> <!-- item-container -->

app/views/employees/_new_employee_form.html.erb
<div id="new_employee_form_wrapper" class="hidden">
	
	<div id="new_employee_form">
		<h2>Add New Employee</h2>
		<% form_for @new_employee, :html => { :multipart => true } do |form| %>
			<table>
				<tr>
					<td class="label">
						<%= form.label :name%>
					</td>
					<td class="value">
						<%= form.text_field :name %>
					</td>
				</tr>
			
				<tr>
					<td class="label">
						<%= form.label :nik%>
					</td>
					<td class="value">
						<%= form.text_field :nik %>
					</td>
				</tr>
				
				
				<tr>
					<td class="label">
						<%= form.label :division_id%>
					</td>
					<td class="value">
						<%#= form.select(:division_id , @new_employee.department_selections , {:prompt => "Pilih Divisi"}) %>
						<!-- see this shite http://railsforum.com/viewtopic.php?id=15326 
						http://shiningthrough.co.uk/Select-helper-methods-in-Ruby-on-Rails
						-->
						
						<%= form.select(:division_id, grouped_options_for_select(Employee.grouped_selection_for_divisions) )%>
						
			
						
					</td>
				</tr>
				
	
				
				
				
				<tr>
					<td class="label">
						<%= form.label :position_id%>
					</td>
					<td class="value">
						<%= form.select(:position_id , Employee.position_selections , {:prompt => "Pilih Jabatan"}) %>
						<!-- see this shite http://railsforum.com/viewtopic.php?id=15326 
						http://shiningthrough.co.uk/Select-helper-methods-in-Ruby-on-Rails
						-->
					</td>
				</tr>
				
				<tr>
					<td class="label">
						<%= form.label :photo%>
					</td>
					<td class="value">
						<%= form.file_field :photo %>
					</td>
				</tr>
				
				<tr>
					<td class="label">
						<%= form.label :starting_date%>
					</td>
					<td class="value">
						<%= form.date_select :starting_date %>
					</td>
				</tr>
			</table>
			<%= form.submit %>
		<% end %>
	
	
	</div> <!-- #new_employee_form -->
</div>  <!-- #new_employee_form_wrapper -->

app/views/employees/create.html.erb
Hehehe, a new employee is created

<br />
<% if @text %>
	<div class="error"><%= @text %> </div>
<% end %>


<%= "The employee is #{@employee}"  %>
<br />
<%= "#{@employee.errors}"%>
<ul>
	<% for method in @employee.methods %>
		<li><%=  method %></li>
	<% end %>
</ul>
Name : <%= @employee.name%>

app/views/employees/crop.html.erb
<% content_for (:head) do %>  
	<%= stylesheet_link_tag "jquery.Jcrop" %>  
	<%= javascript_include_tag "jquery.Jcrop.min" %>  
	<script type="text/javascript"> 
		$(function() {  
			$('#cropbox').Jcrop({  
				onChange: update_crop,  
				onSelect: update_crop,  
				setSelect: [0, 0, 500, 500],  
				aspectRatio: 1  
			});  
		});

		function update_crop(coords) {  
			var ratio = <%= @employee.photo_geometry(:original).width %> / <%= @employee.photo_geometry(:large).width %>;   
			$('#crop_x').val(Math.floor(coords.x * ratio));  
			$('#crop_y').val(Math.floor(coords.y * ratio));  
			$('#crop_w').val(Math.floor(coords.w * ratio));  
			$('#crop_h').val(Math.floor(coords.h * ratio));    
		}
	</script>
<% end %> 


<%= image_tag @employee.photo.url(:large), :id => "cropbox" %>  

<% form_for @employee do |form| %>  
	<% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>  
		<%= form.hidden_field attribute, :id => attribute %>  
	<% end %>
	<p><%= form.submit "Crop" %></p>  
<% end %>

app/views/employees/index.html.erb
<%= link_to "New Employee" , "#new_employee_form" , :id=>"new_employee"%>


<%#= render :partial => "new_employee_form" %>
<div id="new_employee_form_wrapper" class="hidden">
	
	<div id="new_employee_form">
		<h2>Add New Employee</h2>
		<% form_for @new_employee, :html => { :multipart => true } do |form| %>
			<table>
				<tr>
					<td class="label">
						<%= form.label :name%>
					</td>
					<td class="value">
						<%= form.text_field :name %>
					</td>
				</tr>
			
				<tr>
					<td class="label">
						<%= form.label :nik%>
					</td>
					<td class="value">
						<%= form.text_field :nik %>
					</td>
				</tr>
				
				
				<tr>
					<td class="label">
						<%= form.label :division_id%>
					</td>
					<td class="value">
						<%#= form.select(:division_id , @new_employee.department_selections , {:prompt => "Pilih Divisi"}) %>
						<!-- see this shite http://railsforum.com/viewtopic.php?id=15326 
						http://shiningthrough.co.uk/Select-helper-methods-in-Ruby-on-Rails
						-->
						
						<%= form.select(:division_id, grouped_options_for_select(Employee.grouped_selection_for_divisions) )%>
						
			
						
					</td>
				</tr>
				
	
				
				
				
				<tr>
					<td class="label">
						<%= form.label :position_id%>
					</td>
					<td class="value">
						<%= form.select(:position_id , Employee.position_selections , {:prompt => "Pilih Jabatan"}) %>
						<!-- see this shite http://railsforum.com/viewtopic.php?id=15326 
						http://shiningthrough.co.uk/Select-helper-methods-in-Ruby-on-Rails
						-->
					</td>
				</tr>
				
				<tr>
					<td class="label">
						<%= form.label :photo%>
					</td>
					<td class="value">
						<%= form.file_field :photo %>
					</td>
				</tr>
				
				<tr>
					<td class="label">
						<%= form.label :starting_date%>
					</td>
					<td class="value">
						<%= form.date_select :starting_date %>
					</td>
				</tr>
			</table>
			<%= form.submit %>
		<% end %>
	
	
	</div> <!-- #new_employee_form -->
</div>  <!-- #new_employee_form_wrapper -->


<ul id="employee_feed">
	<% for employee in @employees %>
		<div>
			<% link_to employee_path(employee)  do %>
				<%= image_tag employee.photo.url(:small) %>
			<% end %>
			
			<%= link_to "#{employee.name}", employee_path(employee)%>
		</div>
	<% end %>
</ul>

app/views/employees/new.html.erb
<% form_for @employee, :html => { :multipart => true } do |form| %>
	<%= form.text_field :name %>
 	<%= form.file_field :photo %>
	<%= form.submit %>
<% end %>

app/views/employees/show.html.erb
<%= render :partial => "brief_profile", :locals => { :employee => @employee } %>


<div class="profile-content-details clearfix">
	<div class="main-profile-content">
		
		<div class="main-profile-header grey-bar">
			Employment History
		</div> <!-- main-profile-header grey-bar -->
		
		<div class="main-profile-body sub-content ui-sortable">
			<%= render :partial => "employee_details" %>
		</div> <!-- main-profile-body sub-content ui-sortable -->
		
		
		
	</div><!-- main-profile-content -->
	
	<div class="sidebar-menu wd">
		<div class="sidebar-header grey-bar">
			Critical Statistics
		</div>
		
		<div style="margin-top: 20px;">
			<div class="social-media-resource clearfix">
				<%= "80% Attendance"%>
			</div>
			
			<div class="social-media-resource clearfix">
				<%= "7 hari cuti tersisa" %>
			</div>
			
		</div>
	</div> <!-- sidebar-menu -->
	
</div><!-- profile-content-details -->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Hrita</title>
  <%= stylesheet_link_tag :flutie, 'boilerplate', 'base','jquery.fancybox-1.3.4' , 'application' %>
	<%#= stylesheet_link_tag :flutie, 'admin', :cache => true %>
	<%= javascript_include_tag 'jquery.1.5.1.min', "jquery.fancybox-1.3.4.pack" %> 
  <%= csrf_meta_tag %>
	<%= yield(:head) %>  
	<%= javascript_include_tag 'application' %> 
</head>

<body>
	<div class="faux-wrapper">
		<div class="header">
			<a id="logo" href="/">Harita</a>
			
			<div class="user-info">
				
				<div id="user_nav">  
				  <% if user_signed_in? %>  
				    <%= current_user.email %> 
				    <%= link_to "Sign out", destroy_user_session_path %>  
				  <% else %>  
				    <%#= link_to "Sign up", new_user_registration_path %> or  
				    <%= link_to "Sign in", new_user_session_path %>  
				  <% end %>  
				</div>
				
				
			</div>
		</div><!-- header -->
		
		<div class="nav-bar blue-bar">
			<%= link_to "Home", employees_path %>
			<ul class="menu clearfix">
				<li>
					<a href="#">Attendance</a>
				</li
				
				<li>
					<a href="#">History</a>
				</li
			</ul> 
		</div><!-- nav-bar -->
	
		<%= yield %>
	</div><!-- faux-wrapper -- >
</body>
</html>